version: "3.7"

services:

    obsidian:
        image: obsidian
        build:
          context: .
          dockerfile: Dockerfile
          args:
            buildno: 1
          labels:
            - "com.example.description=Local Node Tests"
            - "com.example.department=Engineering"
            - "com.example.label-no-value"
        volumes:
            - "./../project:/repo"
        stdin_open: true
        tty: true
